#!/usr/bin/env bash
# This script configures a new Ubuntu machine to respect some requirements
sudo apt-get update
sudo apt-get install -y nginx
sudo echo "Hello world!" > /var/www/html/index.nginx-debian.html
sudo printf %s "server {
     listen 	 80 default_server;
     listen 	 [::]:80 default_server;
     root 	 /etc/nginx/html;
     index 	 index.html index.htm index.nginx-debian.html;
}
" > /etc/nginx/sites-available/default
sudo service nginx restart
