#!/usr/bin/env bash
# This script configures a new Ubuntu machine to respect some requirements
sudo apt-get -y install nginx && sudo ufw allow 'Nginx HTTP' && echo "Hello world!" > sudo /var/www/html/index.nginx-debian.html
