#!/usr/bin/env bash
# This script configures your Nginx server so that /redirect me is redirecting to another page
sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello world!" > /etc/nginx/html/index.html
printf %s "server {
	listen 		80 default_server;
	listen		[::]:80 default_server;
	root		/etc/nginx/html;
	index		index.html index.htm;
	server_name 	_;

	location /redirect_me {
		return 301 http://facebook.com/;
	}
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
