#!/usr/bin/env bash
# This script configures your Nginx server to have a custom 404 page that
# contains the string 'Ceci n'est pas une page'
sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello world!" > /etc/nginx/html/index.html
printf %s "server {
	listen 		80 default_server;
	listen		[::]:80 default_server;
	root		/etc/nginx/html;
	index		index.html index.htm;
	server_name 	_;

	location /redirect_me {
		return 301 http://facebook.com/;
	}

	location /xyz {
		return 404 'Ceci n\'est pas une page\n';
	}
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
