#!/usr/bin/env bash
# This script installs and configures haproxy on a server
sudo apt update
sudo apt install -y haproxy
printf %s "frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend

backend web-backend
	balance roundrobin
	server web-01 54.236.28.52:80 check
	server web-02 18.234.105.212:80 check
	" > /etc/haproxy/haproxy.cfg
sudo service haproxy restart
