#!/usr/bin/env bash
# This script displays "Best School" 10 times
for i in 'Best School' 'Best School' 'Best School' 'Best School' 'Best School' 'Best School' 'Best School' 'Best School' 'Best School' 'Best School'; do echo "$i"; done
