#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes:
# displays hours from 0 to 12
# displays minutes from 1 to 59
i=0
while [ $i -lt 13 ]
do echo "Hour: $i"
	j=1
	while [ $j -lt 60 ]
	do echo "$j"
		(("j += 1"))
	done
	(("i += 1"))
done

