#!/usr/bin/env bash
# This script displays:
# The content of the current directory
# in a list format
# Where the only part of the name after the first dash is displayed
list=$(ls)
for i in $list;
do
	echo "$i" | cut -d '-' -f2
done
