#!/usr/bin/env bash
# This script is a copy of the '1-run_nginx_as_nginx' script, only shorter
chmod 644 /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-enabled/default | sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/80 default_server ipv6only=on;/8080 default_server ipv6only=on;/g' /etc/nginx/sites-enabled/default | sed -i 's/80 default_server ipv6only=on/8080 default_server ipv6only=on;/g' /etc/nginx/sites-available/default
kill "$(pgrep apache2 | head -n 1)"
sudo -u nginx service nginx start
